#!/bin/sh

go test -coverpkg=./... -shuffle=on -v -count=1 -race -failfast -timeout=30s -covermode=atomic -coverprofile=coverage.out ./...
go tool cover -func=coverage.out | grep "total:" | grep "(statements)"